services:
- type: web
  name: electromart
  runtime: php
  plan: free
  buildCommand: composer install
  startCommand: vendor/bin/heroku-php-apache2 ./
  envVars:
    - key: DB_HOST
      scope: run
    - key: DB_USER
      scope: run
    - key: DB_PASS
      scope: run
    - key: DB_NAME
      scope: run
    - key: BASE_URL
      scope: run
